all: iolist proclist ioarp

clean:
	@rm -rf \
	01/iolist \
	02/proclist \
	03/ioarp
	
iolist:
	gcc -o 01/iolist 01/iolist.c
	
proclist:
	gcc -o 02/proclist 02/proclist.c
	
ioarp:
	gcc -o 03/ioarp 03/ioarp.c
	
