all: iolist proclist ioarp iomac ioaddr

clean:
	@rm -rf \
	01/iolist \
	02/proclist \
	03/ioarp \
	04/iomac \
	05/ioaddr
	
iolist:
	gcc -o 01/iolist 01/iolist.c
	
proclist:
	gcc -o 02/proclist 02/proclist.c
	
ioarp:
	gcc -o 03/ioarp 03/ioarp.c

iomac:
	gcc -o 04/iomac 04/iomac.c

ioaddr:
	gcc -o 05/ioaddr 05/ioaddr.c
	
